### PR TITLE
feat(test): test anyof+oneof traversal

### PR DESCRIPTION
**Pull request by meowsbits**
Rel https://github.com/json-schema-tools/traverse/issues/18

This test is currently failing.

### CODE REVIEW

**Comment by meowsbits** [comment]
Is this (the proposed test schema) even a valid schema? Is the behavior defined?

**Comment by BelfordZ** [comment]
lmk if we should reopen for any reason, but as discussed, nesting anyof/oneof etc is fine, but same level, only one is observed.

**Comment by meowsbits** [comment]
@BelfordZ can you remember the citation you found saying that "only one is observed" ? I'm looking through the spec (again...) and can't seem to find it with my `ctrl+f` ing...

**Comment by meowsbits** [comment]
Here's

> It is important to note that the schemas listed in an allOf, anyOf or oneOf array know nothing of one another. While it might be surprising, allOf can not be used to “extend” a schema to add more details to it in the sense of object-oriented inheritance.
> https://json-schema.org/understanding-json-schema/reference/combining.html#id5

Which seems related...

**Pull request closed without merging**
